# Configuration script to Travis-CI
language: python
python:
  - "3.7"
  - "3.8"
install:
  - pip install pipenv coveralls[yaml]
  - pipenv install --dev
script:
  - pytest --cov=ovshell --cov=ovshell_core --cov=ovshell_xcsoar --cov=ovshell_fileman --cov=ovshell_connman --cov-report=term tests
  - black --check setup.py src tests
  - mypy src tests
after_success:
  coveralls
